### ISSUE TITLE
Melhorar documentação do back-end

### ISSUE THREAD

**Issue by davidedup** [Guardians-DSC/iarl-nodejs#100]
Atualizar READ.me para melhor documentar a execução em modo de teste e produção em contêiner.

**Comment by dfquaresma** [comment]
Mais especificamente, documentar o deploy com conteineres.

**Comment by amintasvrp** [comment]
Consegui subir localmente usando a configuração atual. Acho interessante fechar a _issue_ e, caso necessário, abrimos outra.
