### ISSUE TITLE
Download mechanism

### ISSUE THREAD

**Issue by danielrcoura** [Guardians-DSC/iarl-nodejs#14]
How will we handle the downloads? Is it easy to download from the server that is running the application, but the other two?

**Comment by danielrcoura** [comment]
Could have an FTP server on each server, when requesting the download, would be redirected to the appropriate FTP link.

**Comment by dfquaresma** [comment]
Sound nice to me. Another path to solve it would be using ssh and download it as the client would do without our application. The library that we are using now gives us such possibility? Is it more or less simples than what you suggest? I believe both works.

**Comment by danielrcoura** [comment]
I think this way it would be less efficient, since it would have to download from another server to the server that is running the application, which costs time and more operations (which leaves it susceptible to more problems).

**Comment by danielrcoura** [comment]
It has been decided that all servers will run the application. So if you need to change servers, the user will be redirected to the appropriate server.

**Comment by dfquaresma** [comment]
I think we may let this issue open until the feature be satisfied and close it with a PR or multiples PR. If the feature is already satisfied, plese close again.

**Comment by dfquaresma** [comment]
I think we may let this issue open until the feature be satisfied and close it with a PR or multiples PR. If the feature is already satisfied, plese close again.
