### ISSUE TITLE
Refactor directory listing response

### ISSUE THREAD

**Issue by danielrcoura** [Guardians-DSC/iarl-nodejs#59]
Add a path variable in the response to indicate the current path.

```
"path": "/home/Documents/",
"items": [
    {
        "name": "dir1",
        "isFile": false
    }
]
```

**Comment by felipemarinho97** [comment]
i suggest also to put a _filetype_ and _permissions_ field in item body
e.g. _filetype_ `".png", ".py"`
e.g. _permissions_ `drwxr-xr-x`

the field _permissions_ should make _isFile_ deprecated because  **`d`**`rwxr-xr-x` represents a directory

**Comment by danielrcoura** [comment]
Good sugestion!
I think it's best to keep the isFile because it's simpler for the client, also, to get permissions, we need to use [Stats.mode](https://github.com/nodejs/node-v0.x-archive/issues/3045), which returns a numeric type that we have to translate to the `rwxr-xr-x` format, that is, extracting the **d** is more complex.
