### ISSUE TITLE
Track code quality

### ISSUE THREAD

**Issue by matheuscmelo** [Guardians-DSC/iarl-nodejs#61]
it would be nice if we track the code quality of this repository.
there are some GitHub apps that review the code automatically after every PR or commit, I recommend [CodeBeat](https://github.com/marketplace/codebeat). it searches the code for bad smells and report them.
if this suggestion is well accepted, i can easily configure it for this repository.

**Comment by danielrcoura** [comment]
Good suggestion! It would be a great help.

**Comment by matheuscmelo** [comment]
@dfquaresma please add me as contributor so I can do it
